export type CardPalette = 'warm' | 'green' | 'blue' | 'purple' | 'red' | 'indigo' | 'gold' | 'cyan';

export interface WeekendCardVariant {
    emoji: string;
    label: string;
    title: string;
    sub: string;
    accent: string;
    glow: string;
    background: string;
    particles: CardPalette;
}

export const PARTICLE_COLORS: Record<CardPalette, string[]> = {
    warm: ['#f59e0b', '#fb923c', '#fcd34d'],
    green: ['#22c55e', '#86efac', '#4ade80'],
    blue: ['#38bdf8', '#7dd3fc', '#0ea5e9'],
    purple: ['#a855f7', '#d8b4fe', '#c084fc'],
    red: ['#ef4444', '#fca5a5', '#f87171'],
    indigo: ['#818cf8', '#a5b4fc', '#6366f1'],
    gold: ['#facc15', '#fde68a', '#f59e0b'],
    cyan: ['#06b6d4', '#67e8f9', '#22d3ee'],
};

export const CARD_VARIANTS: Record<'ru' | 'kz' | 'en', WeekendCardVariant[]> = {
    ru: [
        {
            emoji: '☕',
            label: 'выходной',
            title: 'Никаких пар сегодня',
            sub: 'Самое время потупить в потолок и назвать это саморефлексией',
            background: 'radial-gradient(ellipse at 20% 80%, #2d1b00 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #1a0e00)',
            accent: '#f59e0b',
            glow: 'rgba(var(--status-warning-rgb), 0.4)',
            particles: 'warm',
        },
        {
            emoji: '🎮',
            label: 'режим зомби',
            title: 'Ещё одну игру и всё',
            sub: 'Так говорят уже 4 часа. Это ложь, но красивая',
            background: 'radial-gradient(ellipse at 80% 20%, #0d1f0d 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #001a00)',
            accent: '#22c55e',
            glow: 'rgba(34, 197, 94, 0.4)',
            particles: 'green',
        },
        {
            emoji: '🌊',
            label: 'поток',
            title: 'Поймал волну',
            sub: 'Наушники, плейлист, окно — и ты уже немного в другой вселенной',
            background: 'radial-gradient(ellipse at 50% 100%, #001a2e 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #001a2e)',
            accent: '#38bdf8',
            glow: 'rgba(56, 189, 248, 0.4)',
            particles: 'blue',
        },
        {
            emoji: '📚',
            label: 'может быть',
            title: 'Сегодня точно позанимаюсь',
            sub: 'Открыл учебник. Закрыл. Открыл YouTube. Это тоже образование',
            background: 'radial-gradient(ellipse at 10% 30%, #1a0a2e 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #120024)',
            accent: '#a855f7',
            glow: 'rgba(168, 85, 247, 0.4)',
            particles: 'purple',
        },
        {
            emoji: '🍕',
            label: 'приоритеты',
            title: 'Еда — это главное',
            sub: 'Физиологические потребности по Маслоу. Ты просто следуешь пирамиде',
            background: 'radial-gradient(ellipse at 70% 70%, #2d0000 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #1a0000)',
            accent: '#ef4444',
            glow: 'rgba(var(--status-danger-rgb), 0.4)',
            particles: 'red',
        },
        {
            emoji: '💤',
            label: 'восстановление',
            title: 'Сон — это продуктивность',
            sub: 'Ты буквально обрабатываешь информацию. Это наука. Спи смело',
            background: 'radial-gradient(ellipse at 50% 50%, #0a0a1a 0%, #0b1120 80%)',
            accent: '#818cf8',
            glow: 'rgba(129, 140, 248, 0.35)',
            particles: 'indigo',
        },
        {
            emoji: '🐈',
            label: 'контент',
            title: 'Я изучаю культуру',
            sub: 'Три часа мемов — это антропология. Докторская степень уже близко',
            background: 'radial-gradient(ellipse at 30% 60%, #1a1200 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #1a0e00)',
            accent: '#facc15',
            glow: 'rgba(250, 204, 21, 0.4)',
            particles: 'gold',
        },
        {
            emoji: '🚀',
            label: 'большие планы',
            title: 'Сегодня всё изменится',
            sub: 'Список дел написан. Мотивация есть. Прокрастинация тоже здесь',
            background: 'radial-gradient(ellipse at 90% 10%, #001020 0%, #0b1120 55%), linear-gradient(160deg, #0b1120, #001a1a)',
            accent: '#06b6d4',
            glow: 'rgba(6, 182, 212, 0.4)',
            particles: 'cyan',
        },
    ],
    kz: [
        {
            emoji: '☕',
            label: 'демалыс',
            title: 'Бүгін сабақ жоқ',
            sub: 'Төбеге қарап отырып, оны өзін-өзі тану деп атауға таптырмас уақыт',
            background: 'radial-gradient(ellipse at 20% 80%, #2d1b00 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #1a0e00)',
            accent: '#f59e0b',
            glow: 'rgba(var(--status-warning-rgb), 0.4)',
            particles: 'warm',
        },
        {
            emoji: '🎮',
            label: 'зомби режимі',
            title: 'Тағы бір ойын ғана',
            sub: 'Мұны төрт сағаттан бері айтып жүрсің. Әдемі өтірік болса да, өтірік',
            background: 'radial-gradient(ellipse at 80% 20%, #0d1f0d 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #001a00)',
            accent: '#22c55e',
            glow: 'rgba(34, 197, 94, 0.4)',
            particles: 'green',
        },
        {
            emoji: '🌊',
            label: 'ағын',
            title: 'Ырғаққа түстің',
            sub: 'Құлаққап, плейлист, терезе — енді сен басқа бір әлемдесің',
            background: 'radial-gradient(ellipse at 50% 100%, #001a2e 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #001a2e)',
            accent: '#38bdf8',
            glow: 'rgba(56, 189, 248, 0.4)',
            particles: 'blue',
        },
        {
            emoji: '📚',
            label: 'мүмкін',
            title: 'Бүгін нақты оқимын',
            sub: 'Оқулықты аштың. Жаптың. YouTube-ты аштың. Бұл да білім ғой',
            background: 'radial-gradient(ellipse at 10% 30%, #1a0a2e 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #120024)',
            accent: '#a855f7',
            glow: 'rgba(168, 85, 247, 0.4)',
            particles: 'purple',
        },
        {
            emoji: '🍕',
            label: 'басымдықтар',
            title: 'Тамақ — бастысы',
            sub: 'Маслоу пирамидасы бойынша бәрі дұрыс. Сен тек жүйеге еріп жүрсің',
            background: 'radial-gradient(ellipse at 70% 70%, #2d0000 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #1a0000)',
            accent: '#ef4444',
            glow: 'rgba(var(--status-danger-rgb), 0.4)',
            particles: 'red',
        },
        {
            emoji: '💤',
            label: 'қалпына келу',
            title: 'Ұйқы — өнімділік',
            sub: 'Ақпаратты миың өңдеп жатыр. Бұл ғылым. Ендеше ұйықтай бер',
            background: 'radial-gradient(ellipse at 50% 50%, #0a0a1a 0%, #0b1120 80%)',
            accent: '#818cf8',
            glow: 'rgba(129, 140, 248, 0.35)',
            particles: 'indigo',
        },
        {
            emoji: '🐈',
            label: 'контент',
            title: 'Мен мәдениет зерттеп жүрмін',
            sub: 'Үш сағат мем қарау — бұл антропология. Докторлық та алыс емес',
            background: 'radial-gradient(ellipse at 30% 60%, #1a1200 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #1a0e00)',
            accent: '#facc15',
            glow: 'rgba(250, 204, 21, 0.4)',
            particles: 'gold',
        },
        {
            emoji: '🚀',
            label: 'үлкен жоспарлар',
            title: 'Бүгін бәрі өзгереді',
            sub: 'Істер тізімі дайын. Мотивация бар. Прокрастинация да осында',
            background: 'radial-gradient(ellipse at 90% 10%, #001020 0%, #0b1120 55%), linear-gradient(160deg, #0b1120, #001a1a)',
            accent: '#06b6d4',
            glow: 'rgba(6, 182, 212, 0.4)',
            particles: 'cyan',
        },
    ],
    en: [
        {
            emoji: '☕',
            label: 'day off',
            title: 'No classes today',
            sub: 'A perfect time to stare at the ceiling and call it self-reflection',
            background: 'radial-gradient(ellipse at 20% 80%, #2d1b00 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #1a0e00)',
            accent: '#f59e0b',
            glow: 'rgba(var(--status-warning-rgb), 0.4)',
            particles: 'warm',
        },
        {
            emoji: '🎮',
            label: 'zombie mode',
            title: 'One more game and that is it',
            sub: 'You have been saying that for four hours. It is a lie, but a beautiful one',
            background: 'radial-gradient(ellipse at 80% 20%, #0d1f0d 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #001a00)',
            accent: '#22c55e',
            glow: 'rgba(34, 197, 94, 0.4)',
            particles: 'green',
        },
        {
            emoji: '🌊',
            label: 'flow',
            title: 'Caught the wave',
            sub: 'Headphones, playlist, window view — and you are already in another universe',
            background: 'radial-gradient(ellipse at 50% 100%, #001a2e 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #001a2e)',
            accent: '#38bdf8',
            glow: 'rgba(56, 189, 248, 0.4)',
            particles: 'blue',
        },
        {
            emoji: '📚',
            label: 'maybe',
            title: 'I will definitely study today',
            sub: 'Opened the textbook. Closed it. Opened YouTube. That still counts as education',
            background: 'radial-gradient(ellipse at 10% 30%, #1a0a2e 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #120024)',
            accent: '#a855f7',
            glow: 'rgba(168, 85, 247, 0.4)',
            particles: 'purple',
        },
        {
            emoji: '🍕',
            label: 'priorities',
            title: 'Food comes first',
            sub: 'Pure Maslow hierarchy. You are just following the pyramid',
            background: 'radial-gradient(ellipse at 70% 70%, #2d0000 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #1a0000)',
            accent: '#ef4444',
            glow: 'rgba(var(--status-danger-rgb), 0.4)',
            particles: 'red',
        },
        {
            emoji: '💤',
            label: 'recovery',
            title: 'Sleep is productivity',
            sub: 'Your brain is literally processing information. That is science. Sleep freely',
            background: 'radial-gradient(ellipse at 50% 50%, #0a0a1a 0%, #0b1120 80%)',
            accent: '#818cf8',
            glow: 'rgba(129, 140, 248, 0.35)',
            particles: 'indigo',
        },
        {
            emoji: '🐈',
            label: 'content',
            title: 'I am studying culture',
            sub: 'Three hours of memes is anthropology. That doctorate is getting close',
            background: 'radial-gradient(ellipse at 30% 60%, #1a1200 0%, #0b1120 55%), linear-gradient(135deg, #0b1120, #1a0e00)',
            accent: '#facc15',
            glow: 'rgba(250, 204, 21, 0.4)',
            particles: 'gold',
        },
        {
            emoji: '🚀',
            label: 'big plans',
            title: 'Today changes everything',
            sub: 'The to-do list is ready. Motivation is here. Procrastination too',
            background: 'radial-gradient(ellipse at 90% 10%, #001020 0%, #0b1120 55%), linear-gradient(160deg, #0b1120, #001a1a)',
            accent: '#06b6d4',
            glow: 'rgba(6, 182, 212, 0.4)',
            particles: 'cyan',
        },
    ],
};
