import type { CoordinatorUi } from './types';

export function getUi(language: 'ru' | 'kz' | 'en'): CoordinatorUi {
    if (language === 'en') {
        return {
            title: 'Coordinator workspace',
            subtitle: 'A full group directory with role controls, contacts, and broadcast announcements for starostas.',
            groups: 'Groups',
            groupsHint: 'Open any group, inspect its roster, and update roles in place.',
            groupSearch: 'Search by title or groupKey',
            oversight: 'Problem groups',
            oversightHint: 'Jump straight to groups that still need a responsible person or have no members at all.',
            filterAll: 'All',
            filterWithRoles: 'With roles',
            filterWithoutStarosta: 'No starosta',
            filterWithoutHelper: 'No helper',
            filterWithMembers: 'With members',
            filterEmpty: 'Empty',
            broadcasts: 'Coordinator broadcasts',
            broadcastsHint: 'Announcements here appear in starosta workspaces for the targeted groups.',
            createGroup: 'Create group',
            editGroup: 'Edit group',
            openSpace: 'Open space',
            collapse: 'Collapse',
            expand: 'Expand',
            loading: 'Loading…',
            loadFailed: 'Failed to load coordinator workspace',
            noGroups: 'No groups have been discovered yet.',
            members: 'Members',
            memberFilter: 'Filter members by name or login',
            noMembers: 'No members found for this group.',
            responsibles: 'Current roles',
            noResponsibles: 'No starostas or helpers assigned yet.',
            phone: 'Phone',
            phoneMissing: 'Phone not found',
            phoneNotSynced: 'Profile has not been synced yet',
            phoneNotProvided: 'Phone is not listed in the profile',
            showPhone: 'Show phone',
            phoneLoading: 'Loading phone…',
            starosta: 'Starosta',
            helper: 'Helper',
            memberSince: 'Joined',
            manualMember: 'Manual',
            autoMember: 'Platonus',
            assignStarosta: 'Assign starosta',
            revokeStarosta: 'Revoke starosta',
            assignHelper: 'Assign helper',
            revokeHelper: 'Revoke helper',
            announcementTitle: 'Announcement title',
            announcementBody: 'Announcement text',
            announcementPriority: 'Priority',
            priorityInfo: 'Info',
            priorityWarning: 'Warning',
            priorityCritical: 'Critical',
            announcementTargeting: 'Audience',
            allStarostas: 'All starostas',
            selectedGroups: 'Specific groups',
            expiresAt: 'Expires at',
            publish: 'Publish announcement',
            recentAnnouncements: 'Recent announcements',
            noAnnouncements: 'No coordinator announcements yet.',
            revokeAnnouncement: 'Revoke',
            active: 'Active',
            expired: 'Expired',
            revoked: 'Revoked',
            targetedGroups: 'Target groups',
            allGroupsBadge: 'All starostas',
            createdAt: 'Created',
            viewCount: 'Views',
            groupTitle: 'Title',
            groupKey: 'groupKey',
            save: 'Save',
        };
    }

    if (language === 'kz') {
        return {
            title: 'Координатор кеңістігі',
            subtitle: 'Топтар каталогы, рөлдерді жылдам ауыстыру, байланыс нөмірлері және старосталарға арналған жаһандық хабарламалар.',
            groups: 'Топтар',
            groupsHint: 'Кез келген топты ашып, қатысушыларды қарап, рөлдерді сол жерде ауыстырыңыз.',
            groupSearch: 'Атауы немесе groupKey бойынша іздеу',
            oversight: 'Проблемалы топтар',
            oversightHint: 'Жауаптысы жоқ немесе мүлде қатысушысы жоқ топтарға бірден өтіңіз.',
            filterAll: 'Барлығы',
            filterWithRoles: 'Рөлі бар',
            filterWithoutStarosta: 'Старостасыз',
            filterWithoutHelper: 'Көмекшісіз',
            filterWithMembers: 'Қатысушысы бар',
            filterEmpty: 'Бос',
            broadcasts: 'Координатор хабарламалары',
            broadcastsHint: 'Мұндағы хабарламалар таңдалған топтардың староста кеңістігінде көрсетіледі.',
            createGroup: 'Топ құру',
            editGroup: 'Топты өңдеу',
            openSpace: 'Кеңістікті ашу',
            collapse: 'Жасыру',
            expand: 'Ашу',
            loading: 'Жүктелуде…',
            loadFailed: 'Координатор кеңістігін жүктеу мүмкін болмады',
            noGroups: 'Әзірге топтар табылған жоқ.',
            members: 'Қатысушылар',
            memberFilter: 'Аты немесе логин бойынша сүзу',
            noMembers: 'Бұл топта қатысушылар табылмады.',
            responsibles: 'Ағымдағы жауаптылар',
            noResponsibles: 'Әзірге староста да, көмекші де тағайындалмаған.',
            phone: 'Телефон',
            phoneMissing: 'Телефон табылмады',
            phoneNotSynced: 'Профиль әлі синхрондалмаған',
            phoneNotProvided: 'Профильде телефон көрсетілмеген',
            showPhone: 'Телефонды көру',
            phoneLoading: 'Телефон жүктелуде…',
            starosta: 'Староста',
            helper: 'Көмекші',
            memberSince: 'Қосылған күні',
            manualMember: 'Қолмен',
            autoMember: 'Platonus',
            assignStarosta: 'Староста ету',
            revokeStarosta: 'Старостаны алу',
            assignHelper: 'Көмекші ету',
            revokeHelper: 'Көмекшіні алу',
            announcementTitle: 'Хабарлама тақырыбы',
            announcementBody: 'Хабарлама мәтіні',
            announcementPriority: 'Маңыздылығы',
            priorityInfo: 'Ақпарат',
            priorityWarning: 'Ескерту',
            priorityCritical: 'Шұғыл',
            announcementTargeting: 'Аудитория',
            allStarostas: 'Барлық старосталар',
            selectedGroups: 'Нақты топтар',
            expiresAt: 'Аяқталу уақыты',
            publish: 'Хабарламаны жариялау',
            recentAnnouncements: 'Соңғы хабарламалар',
            noAnnouncements: 'Координатор хабарламалары әлі жоқ.',
            revokeAnnouncement: 'Тоқтату',
            active: 'Белсенді',
            expired: 'Мерзімі өткен',
            revoked: 'Тоқтатылған',
            targetedGroups: 'Мақсатты топтар',
            allGroupsBadge: 'Барлық старосталар',
            createdAt: 'Жасалған',
            viewCount: 'Қаралым',
            groupTitle: 'Атауы',
            groupKey: 'groupKey',
            save: 'Сақтау',
        };
    }

    return {
        title: 'Пространство координатора',
        subtitle: 'Полный каталог групп с ролями, контактами и глобальными объявлениями для старост.',
        groups: 'Группы',
        groupsHint: 'Открой любую группу, посмотри состав и поменяй роли прямо в списке участников.',
        groupSearch: 'Поиск по названию или groupKey',
        oversight: 'Проблемные группы',
        oversightHint: 'Быстрый переход к группам без ответственных или вообще без участников.',
        filterAll: 'Все',
        filterWithRoles: 'С ролями',
        filterWithoutStarosta: 'Без старосты',
        filterWithoutHelper: 'Без помощника',
        filterWithMembers: 'С участниками',
        filterEmpty: 'Пустые',
        broadcasts: 'Глобальные объявления',
        broadcastsHint: 'Эти сообщения увидят старосты в своих рабочих пространствах.',
        createGroup: 'Создать группу',
        editGroup: 'Изменить группу',
        openSpace: 'Открыть пространство',
        collapse: 'Свернуть',
        expand: 'Раскрыть',
        loading: 'Загрузка…',
        loadFailed: 'Не удалось загрузить пространство координатора',
        noGroups: 'Пока ни одной группы не найдено.',
        members: 'Участники',
        memberFilter: 'Фильтр по ФИО или логину',
        noMembers: 'В этой группе пока нет участников.',
        responsibles: 'Текущие ответственные',
        noResponsibles: 'В этой группе пока не назначены ни староста, ни помощник.',
        phone: 'Телефон',
        phoneMissing: 'Номер не найден',
        phoneNotSynced: 'Профиль этого пользователя ещё не синхронизирован',
        phoneNotProvided: 'В профиле пользователя номер не указан',
        showPhone: 'Показать номер',
        phoneLoading: 'Загружаю номер…',
        starosta: 'Староста',
        helper: 'Помощник',
        memberSince: 'В группе с',
        manualMember: 'Добавлен вручную',
        autoMember: 'Из Platonus',
        assignStarosta: 'Назначить старостой',
        revokeStarosta: 'Снять старосту',
        assignHelper: 'Назначить помощником',
        revokeHelper: 'Снять помощника',
        announcementTitle: 'Заголовок объявления',
        announcementBody: 'Текст объявления',
        announcementPriority: 'Приоритет',
        priorityInfo: 'Инфо',
        priorityWarning: 'Предупреждение',
        priorityCritical: 'Срочно',
        announcementTargeting: 'Кому показать',
        allStarostas: 'Всем старостам',
        selectedGroups: 'Конкретным группам',
        expiresAt: 'Показывать до',
        publish: 'Отправить объявление',
        recentAnnouncements: 'Последние объявления',
        noAnnouncements: 'Пока нет объявлений координатора.',
        revokeAnnouncement: 'Отозвать',
        active: 'Активно',
        expired: 'Истекло',
        revoked: 'Отозвано',
        targetedGroups: 'Целевые группы',
        allGroupsBadge: 'Все старосты',
        createdAt: 'Создано',
        viewCount: 'Просмотры',
        groupTitle: 'Название',
        groupKey: 'groupKey',
        save: 'Сохранить',
    };
}

export function getStatLabels(language: 'ru' | 'kz' | 'en') {
    if (language === 'en') {
        return {
            coordinators: 'Coordinators',
            activeRoles: 'Active roles',
            announcements: 'Announcements',
            mode: 'Coordinator mode',
            focus: 'Current focus',
            focusFallback: 'Pick a group to inspect its members, roles, and contacts.',
            urgent: 'Need attention',
            urgentDetail: 'Groups without starosta or helper are pushed up for faster triage.',
        };
    }
    if (language === 'kz') {
        return {
            coordinators: 'Координаторлар',
            activeRoles: 'Белсенді рөлдер',
            announcements: 'Хабарламалар',
            mode: 'Координатор режимі',
            focus: 'Қазіргі фокус',
            focusFallback: 'Қатысушыларды, рөлдерді және байланыстарды көру үшін топты таңдаңыз.',
            urgent: 'Назар керек',
            urgentDetail: 'Старостасы не көмекшісі жоқ топтар тезірек өңдеу үшін жоғарыға шығады.',
        };
    }
    return {
        coordinators: 'Координаторы',
        activeRoles: 'Активные роли',
        announcements: 'Объявления',
        mode: 'Режим координатора',
        focus: 'Текущий фокус',
        focusFallback: 'Выбери группу, чтобы быстро перейти к составу, ролям и контактам.',
        urgent: 'Требует внимания',
        urgentDetail: 'Группы без старосты или помощника поднимаются выше для быстрой разборки.',
    };
}
