import type { CuratorUi } from './types';

export function getCuratorUi(language: 'ru' | 'kz' | 'en'): CuratorUi {
    if (language === 'en') {
        return {
            title: 'Curator workspace',
            subtitle: 'Students and inbox for the group, without admin clutter.',
            students: 'Students',
            inbox: 'Inbox',
            switchGroup: 'Switch group',
            currentGroup: 'This group is selected now',
            searchPlaceholder: 'Search by name, login, specialty',
            openProfile: 'Open profile',
            approve: 'Approve',
            reject: 'Reject',
            escalate: 'Escalate',
            reviewing: 'Processing…',
            notePlaceholder: 'Decision note',
            inboxHint: 'Join requests and membership disputes for the current group.',
            studentsHint: 'Student cards with profile and academic context instead of a dry registry.',
            noStudents: 'No students found for this group yet.',
            noInbox: 'No pending requests or disputes right now.',
            joinRequests: 'Join requests',
            disputes: 'Membership disputes',
            queueRequest: 'Join request',
            queueDispute: 'Membership dispute',
            roleStarosta: 'Starosta',
            roleHelper: 'Helper',
            roleMember: 'Student',
            fullName: 'Full name',
            group: 'Group',
            role: 'Role',
            specialty: 'Specialty',
            course: 'Course',
            gpa: 'GPA',
            lastActivity: 'Last activity',
            onlineNowLabel: 'Online now',
            assignStarosta: 'Assign starosta',
            revokeStarosta: 'Revoke starosta',
            assignHelper: 'Assign helper',
            revokeHelper: 'Revoke helper',
            close: 'Close',
            summaryLine: '{students} students · {pending} pending · {broadcasts} broadcasts',
            loading: 'Loading…',
            loadError: 'Failed to load curator workspace.',
        };
    }
    if (language === 'kz') {
        return {
            title: 'Куратор кеңістігі',
            subtitle: 'Топ үшін студенттер мен кіріс жәшігі, артық admin шусыз.',
            students: 'Студенттер',
            inbox: 'Кіріс',
            switchGroup: 'Топты ауыстыру',
            currentGroup: 'Қазір осы топ таңдалған',
            searchPlaceholder: 'Аты, логині, мамандығы бойынша іздеу',
            openProfile: 'Профильді ашу',
            approve: 'Бекіту',
            reject: 'Қайтару',
            escalate: 'Эскалация',
            reviewing: 'Өңделуде…',
            notePlaceholder: 'Шешімге түсініктеме',
            inboxHint: 'Ағымдағы топтың өтініштері мен даулары.',
            studentsHint: 'Құрғақ тізімнің орнына профиль мен оқу жиынтығы бар студент карталары.',
            noStudents: 'Бұл топта әзірге студенттер жоқ.',
            noInbox: 'Қазір күтудегі өтініштер мен даулар жоқ.',
            joinRequests: 'Кіру өтініштері',
            disputes: 'Қатысушы даулары',
            queueRequest: 'Топқа өтініш',
            queueDispute: 'Қатысушы дауы',
            roleStarosta: 'Староста',
            roleHelper: 'Көмекші',
            roleMember: 'Студент',
            fullName: 'Толық аты',
            group: 'Топ',
            role: 'Рөл',
            specialty: 'Мамандық',
            course: 'Курс',
            gpa: 'GPA',
            lastActivity: 'Соңғы белсенділік',
            onlineNowLabel: 'Қазір онлайн',
            assignStarosta: 'Староста ету',
            revokeStarosta: 'Старостаны алу',
            assignHelper: 'Көмекші ету',
            revokeHelper: 'Көмекшіні алу',
            close: 'Жабу',
            summaryLine: '{students} студент · {pending} өңделуде · {broadcasts} хабарлама',
            loading: 'Жүктелуде…',
            loadError: 'Куратор кеңістігін жүктеу мүмкін болмады.',
        };
    }
    return {
        title: 'Пространство куратора',
        subtitle: 'Студенты и входящие для группы, без админского шума.',
        students: 'Студенты',
        inbox: 'Входящие',
        switchGroup: 'Сменить группу',
        currentGroup: 'Сейчас выбрана эта группа',
        searchPlaceholder: 'Поиск по имени, логину, специальности',
        openProfile: 'Открыть профиль',
        approve: 'Одобрить',
        reject: 'Отклонить',
        escalate: 'Эскалировать',
        reviewing: 'Обрабатываю…',
        notePlaceholder: 'Комментарий к решению',
        inboxHint: 'Заявки на вступление и споры по участникам текущей группы.',
        studentsHint: 'Карточки студентов с профилем и учебной сводкой вместо сухого реестра.',
        noStudents: 'Для этой группы пока нет студентов.',
        noInbox: 'Сейчас нет ожидающих заявок или споров.',
        joinRequests: 'Заявки на вступление',
        disputes: 'Споры по участникам',
        queueRequest: 'Заявка в группу',
        queueDispute: 'Спор по участнику',
        roleStarosta: 'Староста',
        roleHelper: 'Помощник',
        roleMember: 'Студент',
        fullName: 'ФИО',
        group: 'Группа',
        role: 'Роль',
        specialty: 'Специальность',
        course: 'Курс',
        gpa: 'GPA',
        lastActivity: 'Последняя активность',
        onlineNowLabel: 'Сейчас онлайн',
        assignStarosta: 'Назначить старостой',
        revokeStarosta: 'Снять старосту',
        assignHelper: 'Назначить помощником',
        revokeHelper: 'Снять помощника',
        close: 'Закрыть',
        summaryLine: '{students} студентов · {pending} в обработке · {broadcasts} объявление',
        loading: 'Загрузка…',
        loadError: 'Не удалось загрузить пространство куратора.',
    };
}
