import type { LeaderboardUiCopy } from './types';

const RU: LeaderboardUiCopy = {
    title: 'Зал славы',
    subtitle: 'Люди и преподы, которые прямо сейчас формируют атмосферу приложения.',
    topLabel: 'зал славы',
    refresh: 'Обновить',
    showAll: 'Показать весь рейтинг',
    collapse: 'Свернуть рейтинг',
    loading: 'Собираю рейтинг...',
    empty: 'Пока недостаточно данных активности.',
    error: 'Не удалось загрузить рейтинг.',
    updated: 'Обновлено',
    totalUsers: 'Пользователей',
    yourPlace: 'Ваше место',
    yourTime: 'Ваше время',
    whyNotAll: 'В рейтинг попадают только те, у кого уже появилось зафиксированное время активности.',
    you: 'это вы',
    podiumDay: 'Лидеры дня',
    podiumWeek: 'Лидеры недели',
    podiumAll: 'Лидеры за всё время',
    teachersTitle: 'Рейтинг преподавателей',
    teachersSubtitle: 'Добавляйте преподавателей вручную, ставьте tier и отмечайте вайб тегами.',
    teachersEmpty: 'Пока ни один преподаватель ещё не получил оценку.',
    teachersError: 'Не удалось загрузить рейтинг преподавателей.',
    totalTeachers: 'Преподов в рейтинге',
    totalVotes: 'Всего оценок',
    yourTeacherVotes: 'Ваши оценки',
    studentsTab: 'Студенты',
    subjectsTab: 'Предметы',
    teachersTab: 'Преподы',
    referralsTab: 'Рефералы',
    periodDay: 'За день',
    periodWeek: 'За неделю',
    periodAll: 'За всё время',
    teacherSearchPlaceholder: 'Найти или добавить преподавателя по ФИО',
    teacherSearchHint: 'Если нужного преподавателя нет, можно добавить его вручную.',
    teacherSearchLoading: 'Ищу преподавателей...',
    teacherSearchEmpty: 'Ничего не нашлось. Можно добавить вручную.',
    addTeacher: 'Добавить вручную',
    addingTeacher: 'Добавляю...',
    selectedTeacher: 'Выбранный преподаватель',
    noTeacherSelected: 'Выберите преподавателя из подсказок или добавьте вручную, затем поставьте ему tier.',
    chooseTier: 'Выберите tier',
    chooseTags: 'Выберите теги',
    tagsHint: 'Можно выбрать до 5 тегов. Это чисто студенческий вайб, не официальный рейтинг кафедры.',
    saveTeacherRating: 'Сохранить мою оценку',
    savingTeacherRating: 'Сохраняю...',
    teacherSaved: 'Оценка преподавателя сохранена.',
    teacherFailed: 'Не удалось сохранить оценку преподавателя.',
    teacherVotes: 'оценок',
    teacherYourVote: 'ваш vote',
    sourceProfile: 'есть профиль person.kstu.kz',
    noTopTags: 'Теги ещё не набрались',
    topTeachersDay: 'Топ преподавателей за день',
    topTeachersWeek: 'Топ преподавателей за неделю',
    topTeachersAll: 'Топ преподавателей за всё время',
    teacherRankHint: 'Рейтинг живой: после новых оценок порядок будет меняться.',
    tagLimitReached: 'Лимит тегов: 5',
    seedHint: 'Ваш initial-рейтинг уже загружен как первый голос и дальше будет меняться вместе с общим топом.',
    myRatingCard: 'Моя оценка',
    teacherUnverifiedLabel: 'не подтверждён',
    teacherNameInvalidHint: 'ФИО должно содержать минимум 2 слова, только буквы',
    teacherNotInScheduleTitle: 'Не нашли в вашем расписании',
    teacherNotInScheduleBody: 'Этот преподаватель никогда не был у вас в расписании. Точно правильно?',
    teacherNotInScheduleAddAnyway: 'Добавить всё равно',
    teacherNotInScheduleCancel: 'Отмена',
    teacherCanonicalSuggestionTitle: 'Возможно вы имели в виду',
    teacherCanonicalSuggestionUse: 'Использовать',
    teacherCanonicalSuggestionKeep: 'Оставить как есть',
    referralsTitle: 'Топ рефералов',
    referralsSubtitle: 'Люди, которые приводят новых пользователей в UniverSchedule.',
    referralsEmpty: 'Пока в реферальном топе тихо.',
    referralsError: 'Не удалось загрузить реферальный рейтинг.',
    referralTotalUsers: 'Рефоводов в топе',
    yourReferralPlace: 'Ваше место',
    yourReferralPoints: 'Ваши поинты',
    rewardsTitle: 'Награды за рефералов',
    rewardsHint: 'Badge в профиле и темы открываются по числу успешных приглашений.',
    rewardRefs: 'рефералов',
    rewardThemeSherbet: 'Sherbet Pop',
    rewardThemeNebula: 'Nebula Rush',
    referralsCount: 'рефералов',
    referralPoints: 'поинтов',
    topReferrersDay: 'Топ рефералов за день',
    topReferrersWeek: 'Топ рефералов за неделю',
    topReferrersAll: 'Топ рефералов за всё время',
    timeOnSite: 'Время на сайте',
    subjectsTitle: 'Рейтинг по предметам',
    subjectsSubtitle: 'Лучшие результаты по отдельным дисциплинам внутри общего зала славы.',
    subjectSearchPlaceholder: 'Поиск предмета',
    subjectSearchClear: 'Очистить',
    subjectNoSubjects: 'Пока нет данных',
    subjectNoSubjectsHint: 'Рейтинг наполняется, когда студенты открывают свои оценки.',
    subjectPickTitle: 'Выбери предмет',
    subjectPickHint: 'Выбери дисциплину, чтобы увидеть лучших по ней.',
    subjectErrorTitle: 'Не удалось загрузить',
    subjectRetry: 'Повторить',
    subjectEmptyTitle: 'Здесь пока пусто',
    subjectEmptyHint: 'По этому предмету ещё нет оценок в рейтинге.',
    subjectYourRank: 'Твоё место',
    subjectNotRanked: 'не в рейтинге',
    subjectLearners: 'участников',
    subjectYou: 'Ты',
    subjectMessage: 'Написать',
    subjectOptOutShow: 'Показывать мои баллы',
    subjectOptOutHint: 'С вашим именем или никнеймом. Можно отключить в любой момент.',
    subjectProfileTitle: 'Профиль для зала славы',
    subjectNicknameLabel: 'Никнейм',
    subjectContactsTitle: 'Соцсети для связи',
    subjectContactsHint: 'Необязательно. Покажем рядом с вашим именем в предметных рейтингах.',
    subjectTelegramLabel: 'Telegram',
    subjectInstagramLabel: 'Instagram',
    subjectSaveProfile: 'Сохранить',
    subjectSavingProfile: 'Сохраняю...',
    subjectProfileSaved: 'Профиль рейтинга сохранён.',
    subjectProfileFailed: 'Не удалось сохранить профиль рейтинга.',
};

const KZ: LeaderboardUiCopy = {
    title: 'Белсенділік даңқ залы',
    subtitle: 'Қосымшаның атмосферасын дәл қазір қалыптастырып жүрген адамдар мен оқытушылар.',
    topLabel: 'сайт рейтингі',
    refresh: 'Жаңарту',
    showAll: 'Толық рейтингті ашу',
    collapse: 'Рейтингті жинау',
    loading: 'Рейтинг жиналып жатыр...',
    empty: 'Белсенділік деректері әзірге жеткіліксіз.',
    error: 'Рейтингті жүктеу мүмкін болмады.',
    updated: 'Жаңартылды',
    totalUsers: 'Қолданушылар',
    yourPlace: 'Сіздің орныңыз',
    yourTime: 'Сіздің уақытыңыз',
    whyNotAll: 'Рейтингке тек тіркелген белсенділік уақыты бар қолданушылар кіреді.',
    you: 'бұл сіз',
    podiumDay: 'Күн лидерлері',
    podiumWeek: 'Апта лидерлері',
    podiumAll: 'Барлық уақыт лидерлері',
    teachersTitle: 'Оқытушылар рейтингі',
    teachersSubtitle: 'Оқытушыларды қолмен қосып, tier қойып, вайб-тегтермен бағалаңыз.',
    teachersEmpty: 'Әзірге бірде-бір оқытушы баға алған жоқ.',
    teachersError: 'Оқытушылар рейтингін жүктеу мүмкін болмады.',
    totalTeachers: 'Рейтингтегі оқытушылар',
    totalVotes: 'Барлық бағалар',
    yourTeacherVotes: 'Сіздің бағаларыңыз',
    studentsTab: 'Студенттер',
    subjectsTab: 'Пәндер',
    teachersTab: 'Оқытушылар',
    referralsTab: 'Рефералдар',
    periodDay: 'Күн бойынша',
    periodWeek: 'Апта бойынша',
    periodAll: 'Барлық уақыт',
    teacherSearchPlaceholder: 'Оқытушыны аты-жөні бойынша табу немесе қосу',
    teacherSearchHint: 'Керек оқытушы табылмаса, оны қолмен қосуға болады.',
    teacherSearchLoading: 'Оқытушылар ізделіп жатыр...',
    teacherSearchEmpty: 'Ештеңе табылмады. Қолмен қосуға болады.',
    addTeacher: 'Қолмен қосу',
    addingTeacher: 'Қосылып жатыр...',
    selectedTeacher: 'Таңдалған оқытушы',
    noTeacherSelected: 'Подсказкадан оқытушыны таңдаңыз немесе қолмен қосып, содан кейін tier қойыңыз.',
    chooseTier: 'Tier таңдаңыз',
    chooseTags: 'Тегтерді таңдаңыз',
    tagsHint: 'Ең көбі 5 тег таңдауға болады. Бұл кафедраның ресми рейтингі емес, студенттік вайб.',
    saveTeacherRating: 'Бағамды сақтау',
    savingTeacherRating: 'Сақталып жатыр...',
    teacherSaved: 'Оқытушы бағасы сақталды.',
    teacherFailed: 'Оқытушы бағасын сақтау мүмкін болмады.',
    teacherVotes: 'баға',
    teacherYourVote: 'сіздің бағаңыз',
    sourceProfile: 'person.kstu.kz профилі бар',
    noTopTags: 'Тегтер әлі жиналған жоқ',
    topTeachersDay: 'Күндік топ оқытушылар',
    topTeachersWeek: 'Апталық топ оқытушылар',
    topTeachersAll: 'Барлық уақыт топ оқытушылар',
    teacherRankHint: 'Бұл тірі рейтинг: жаңа бағалар келген сайын реті өзгеріп отырады.',
    tagLimitReached: 'Тег лимиті: 5',
    seedHint: 'Сіздің бастапқы рейтингіңіз бірінші дауыс ретінде жүктелді, әрі қарай жалпы топпен бірге өзгереді.',
    myRatingCard: 'Менің бағам',
    teacherUnverifiedLabel: 'расталмаған',
    teacherNameInvalidHint: 'Аты-жөнінде кемінде 2 сөз болуы керек, тек әріптер',
    teacherNotInScheduleTitle: 'Сіздің сабақ кестеңізде табылмады',
    teacherNotInScheduleBody: 'Бұл оқытушы сіздің сабақ кестеңізде ешқашан болмаған. Шынымен дұрыс па?',
    teacherNotInScheduleAddAnyway: 'Бәрібір қосу',
    teacherNotInScheduleCancel: 'Бас тарту',
    teacherCanonicalSuggestionTitle: 'Мүмкін сіз мынаны айтқыңыз келді',
    teacherCanonicalSuggestionUse: 'Қолдану',
    teacherCanonicalSuggestionKeep: 'Қалдыру',
    referralsTitle: 'Топ рефералдар',
    referralsSubtitle: 'UniverSchedule-ге жаңа адамдарды әкеліп жүргендер.',
    referralsEmpty: 'Реферал топ әзірге бос.',
    referralsError: 'Реферал рейтингін жүктеу мүмкін болмады.',
    referralTotalUsers: 'Топтағы реферал иелері',
    yourReferralPlace: 'Сіздің орныңыз',
    yourReferralPoints: 'Сіздің ұпайыңыз',
    rewardsTitle: 'Реферал сыйақылары',
    rewardsHint: 'Профиль badge-і мен тақырыптар сәтті шақырулар санына қарай ашылады.',
    rewardRefs: 'реферал',
    rewardThemeSherbet: 'Sherbet Pop',
    rewardThemeNebula: 'Nebula Rush',
    referralsCount: 'реферал',
    referralPoints: 'ұпай',
    topReferrersDay: 'Күндік топ рефералдар',
    topReferrersWeek: 'Апталық топ рефералдар',
    topReferrersAll: 'Барлық уақыт топ рефералдар',
    timeOnSite: 'Сайтта өткен уақыт',
    subjectsTitle: 'Пәндер рейтингі',
    subjectsSubtitle: 'Жеке пәндер бойынша үздік нәтижелер жалпы даңқ залында.',
    subjectSearchPlaceholder: 'Пәнді іздеу',
    subjectSearchClear: 'Тазарту',
    subjectNoSubjects: 'Әзірге деректер жоқ',
    subjectNoSubjectsHint: 'Студенттер бағаларын ашқан сайын рейтинг толады.',
    subjectPickTitle: 'Пән таңдаңыз',
    subjectPickHint: 'Осы пән бойынша үздіктерді көру үшін пәнді таңдаңыз.',
    subjectErrorTitle: 'Жүктеу мүмкін болмады',
    subjectRetry: 'Қайталау',
    subjectEmptyTitle: 'Әзірге бос',
    subjectEmptyHint: 'Бұл пән бойынша рейтингте бағалар әлі жоқ.',
    subjectYourRank: 'Сіздің орныңыз',
    subjectNotRanked: 'рейтингте жоқ',
    subjectLearners: 'қатысушы',
    subjectYou: 'Сіз',
    subjectMessage: 'Жазу',
    subjectOptOutShow: 'Менің балдарымды көрсету',
    subjectOptOutHint: 'Атыңызбен немесе никнейммен. Кез келген уақытта өшіруге болады.',
    subjectProfileTitle: 'Даңқ залы профилі',
    subjectNicknameLabel: 'Никнейм',
    subjectContactsTitle: 'Байланыс соцжелілері',
    subjectContactsHint: 'Міндетті емес. Пән рейтингінде атыңыздың жанында көрсетеміз.',
    subjectTelegramLabel: 'Telegram',
    subjectInstagramLabel: 'Instagram',
    subjectSaveProfile: 'Сақтау',
    subjectSavingProfile: 'Сақталуда...',
    subjectProfileSaved: 'Рейтинг профилі сақталды.',
    subjectProfileFailed: 'Рейтинг профилін сақтау мүмкін болмады.',
};

const EN: LeaderboardUiCopy = {
    title: 'Hall of Fame',
    subtitle: 'People and teachers who shape the vibe of the app right now.',
    topLabel: 'hall of fame',
    refresh: 'Refresh',
    showAll: 'Show full ranking',
    collapse: 'Collapse ranking',
    loading: 'Building the leaderboard...',
    empty: 'Not enough activity data yet.',
    error: 'Failed to load the leaderboard.',
    updated: 'Updated',
    totalUsers: 'Users',
    yourPlace: 'Your place',
    yourTime: 'Your time',
    whyNotAll: 'Only users with recorded activity time are included in the ranking.',
    you: 'you',
    podiumDay: 'Leaders of the day',
    podiumWeek: 'Leaders of the week',
    podiumAll: 'All-time leaders',
    teachersTitle: 'Teacher leaderboard',
    teachersSubtitle: 'Add teachers manually, rate them by tier, and mark their vibe with tags.',
    teachersEmpty: 'No teacher has been rated yet.',
    teachersError: 'Failed to load the teacher leaderboard.',
    totalTeachers: 'Ranked teachers',
    totalVotes: 'Total votes',
    yourTeacherVotes: 'Your ratings',
    studentsTab: 'Students',
    subjectsTab: 'Subjects',
    teachersTab: 'Teachers',
    referralsTab: 'Referrals',
    periodDay: 'Today',
    periodWeek: 'This week',
    periodAll: 'All time',
    teacherSearchPlaceholder: 'Find or add a teacher by full name',
    teacherSearchHint: 'If the teacher is missing, you can add them manually.',
    teacherSearchLoading: 'Searching teachers...',
    teacherSearchEmpty: 'No matches yet. You can add this teacher manually.',
    addTeacher: 'Add manually',
    addingTeacher: 'Adding...',
    selectedTeacher: 'Selected teacher',
    noTeacherSelected: 'Pick a teacher from suggestions or add them manually, then set a tier.',
    chooseTier: 'Choose tier',
    chooseTags: 'Choose tags',
    tagsHint: 'You can select up to 5 tags. This is a student vibe layer, not an official faculty rating.',
    saveTeacherRating: 'Save my rating',
    savingTeacherRating: 'Saving...',
    teacherSaved: 'Teacher rating saved.',
    teacherFailed: 'Failed to save teacher rating.',
    teacherVotes: 'votes',
    teacherYourVote: 'your vote',
    sourceProfile: 'has a person.kstu.kz profile',
    noTopTags: 'No top tags yet',
    topTeachersDay: 'Top teachers today',
    topTeachersWeek: 'Top teachers this week',
    topTeachersAll: 'Top teachers all time',
    teacherRankHint: 'This ranking is live: new ratings will keep moving the order.',
    tagLimitReached: 'Tag limit: 5',
    seedHint: 'Your initial list has been loaded as the first vote and will keep evolving with the public ranking.',
    myRatingCard: 'My rating',
    teacherUnverifiedLabel: 'unverified',
    teacherNameInvalidHint: 'Full name must have at least 2 words, letters only',
    teacherNotInScheduleTitle: 'Not found in your schedule',
    teacherNotInScheduleBody: 'This teacher has never appeared in your schedule. Are you sure?',
    teacherNotInScheduleAddAnyway: 'Add anyway',
    teacherNotInScheduleCancel: 'Cancel',
    teacherCanonicalSuggestionTitle: 'Did you mean',
    teacherCanonicalSuggestionUse: 'Use this',
    teacherCanonicalSuggestionKeep: 'Keep as is',
    referralsTitle: 'Top referrers',
    referralsSubtitle: 'People bringing new users into UniverSchedule.',
    referralsEmpty: 'The referral leaderboard is still quiet.',
    referralsError: 'Failed to load referral leaderboard.',
    referralTotalUsers: 'Referrers ranked',
    yourReferralPlace: 'Your place',
    yourReferralPoints: 'Your points',
    rewardsTitle: 'Referral rewards',
    rewardsHint: 'Profile badges and themes unlock based on successful invites.',
    rewardRefs: 'referrals',
    rewardThemeSherbet: 'Sherbet Pop',
    rewardThemeNebula: 'Nebula Rush',
    referralsCount: 'referrals',
    referralPoints: 'points',
    topReferrersDay: 'Top referrers today',
    topReferrersWeek: 'Top referrers this week',
    topReferrersAll: 'Top referrers all time',
    timeOnSite: 'Time on site',
    subjectsTitle: 'Subject ranking',
    subjectsSubtitle: 'Best results by individual subject, now inside the main hall of fame.',
    subjectSearchPlaceholder: 'Search subject',
    subjectSearchClear: 'Clear',
    subjectNoSubjects: 'No data yet',
    subjectNoSubjectsHint: 'The ranking fills as students open their grades.',
    subjectPickTitle: 'Pick a subject',
    subjectPickHint: 'Choose a subject to see the best results for it.',
    subjectErrorTitle: 'Failed to load',
    subjectRetry: 'Retry',
    subjectEmptyTitle: 'Nothing here yet',
    subjectEmptyHint: 'No grades ranked for this subject yet.',
    subjectYourRank: 'Your rank',
    subjectNotRanked: 'not ranked',
    subjectLearners: 'learners',
    subjectYou: 'You',
    subjectMessage: 'Message',
    subjectOptOutShow: 'Show my grades',
    subjectOptOutHint: 'With your name or nickname. You can turn this off anytime.',
    subjectProfileTitle: 'Hall of fame profile',
    subjectNicknameLabel: 'Nickname',
    subjectContactsTitle: 'Social links for contact',
    subjectContactsHint: 'Optional. Shown next to your name in subject rankings.',
    subjectTelegramLabel: 'Telegram',
    subjectInstagramLabel: 'Instagram',
    subjectSaveProfile: 'Save',
    subjectSavingProfile: 'Saving...',
    subjectProfileSaved: 'Ranking profile saved.',
    subjectProfileFailed: 'Failed to save ranking profile.',
};

export function getLeaderboardUi(lang: string): LeaderboardUiCopy {
    if (lang === 'kz') return KZ;
    if (lang === 'en') return EN;
    return RU;
}
